# Netlify configuration file for Perfect-Plate

# This section defines the build settings.
[build]
  # This tells Netlify where your serverless functions are located.
  functions = "api/"
  # This tells Netlify where your main website files are.
  publish = "."

# This is the crucial redirect rule that makes the API proxy work.
# It tells Netlify to route any request starting with /api/ to your functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
